blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.renderPosts, name="posts"),
    path("<int:post_id>", views.post_detail, name="post_detail"),
]

django_porfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from porfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("blog/", include("blog.urls")),
    path("tickets/", views.tickets, name="tickets"),
    path("galeria/", views.galeria, name="galeria"),
    path("guia/", views.guia, name="guia"),
    path("puntos_interes/", views.puntos_interes, name="puntos_interes"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)

porfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="porfolio/images/")
    url = URLField(blank=True)


class Ticket(models.Model):
    title = CharField(max_length=100)
    image = ImageField(upload_to="porfolio/image2/")


class Galeria(models.Model):
    title = CharField(max_length=100)
    image = ImageField(upload_to="porfolio/image3/")

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def renderPosts(request):
    total_posts = Post.objects.count()
    posts = Post.objects.order_by("-date")
    return render(request, "blog.html", {"posts": posts, "total_posts": total_posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

porfolio/views.py
from django.shortcuts import render
from .models import Project, Ticket, Galeria


# Create your views here.
def home(request):
    projects = Project.objects.all()

    return render(request, "home.html", {"projects": projects})


def tickets(request):
    imagenes = Ticket.objects.all()  # Cambiado de 'imagen' a 'imagenes'
    return render(
        request, "tickets.html", {"imagenes": imagenes}
    )  # Cambiado de 'imagen' a 'imagenes'


def galeria(request):
    imagenes = Galeria.objects.all()  # Cambiado de 'imagen' a 'imagenes'
    return render(
        request, "galeria.html", {"imagenes": imagenes}
    )  # Cambiado de 'imagen' a 'imagenes'

def guia(request):
    return render(request, "guia.html")

def puntos_interes(request):
    return render(request, "puntos_interes.html")

blog/templates/blog.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="fs-2">Posts</h1>
<h3>There are {{total_posts}} post{{total_posts|pluralize}}</h3>

{% for post in posts %}

<div class="py-3">

    <div class="card card-body bg-black">
        <div class="row">

            <div class="col-3">
                <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

            </div>
            <div class="col-9">

                <h1>{{post.title}}</h1>
                <p>{{post.description|striptags|truncatechars:100}}</p>
                <p>{{post.date|date:'M d Y'|upper}}</p>

                <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">

    <h1>{{post.title}}</h1>
    <h2 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h2>

    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">


    <div class="my-4">

        {{post.description|safe}}
    </div>
</div>

{% endblock %}

porfolio/templates/galeria.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<style>
    /* Define el tamaño máximo para las imágenes */
    .card {
        position: relative; /* Permite posicionar elementos hijos relativos a este contenedor */
        text-align: center; /* Centra el texto dentro del contenedor */
        background-color: black; /* Establece el color de fondo negro */
        color: white; /* Cambia el color del texto a blanco */
        margin-bottom: 20px; /* Agrega un espacio entre las tarjetas */
    }

    .card-img-top {
        max-width: 100%; /* Establece un ancho máximo para las imágenes */
        height: auto; /* Esto mantendrá la proporción de la imagen */
    }

    .card-title {
        position: absolute; /* Posiciona el título de forma absoluta */
        top: 2px; /* Coloca el título 10px desde la parte superior del contenedor */
        width: 100%; /* Establece el ancho del título al 100% del contenedor */
        margin: 0; /* Elimina cualquier margen que pueda tener el título */
        padding: 0; /* Elimina cualquier relleno que pueda tener el título */
    }
</style>

<h1>Galería de imágenes</h1>
<hr>
<div class="row">
    {% for imagen in imagenes %}
    <div class="col-md-4">
        <div class="card">
            <h2 class="card-title">{{imagen.title}}</h2>
            <img src="{{imagen.image.url }}" class="card-img-top" />
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

porfolio/templates/guia.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #080808;
        color: #f8f4f4;
    }

    section {
        background-color: #030303;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h2 {
        color: #007bff;
        font-size: 24px;
        margin-top: 0;
    }

    h3 {
        color: #e8e4e4;
        font-size: 20px;
        margin-top: 0;
    }

    p {
        font-size: 16px;
    }

    ul, ol {
        padding-left: 20px;
    }

    li {
        margin-bottom: 10px;
    }
</style>

<section>
    <h2>Introducción</h2>
    <p>Bienvenido a la aventura de viajar por el Tren Maya, una experiencia única que te lleva a través de paisajes espectaculares, ruinas antiguas, comunidades locales y una rica diversidad cultural en el sureste de México.</p>
</section>

<section>
    <h2>¿Qué es el Tren Maya?</h2>
    <p>El Tren Maya es un proyecto ferroviario que conectará los estados del sureste mexicano: Chiapas, Tabasco, Campeche, Yucatán y Quintana Roo. Esta iniciativa tiene como objetivo impulsar el turismo en la región, preservar el patrimonio cultural y promover el desarrollo sostenible.</p>
</section>

<section>
    <h2>Destinos Destacados</h2>
    <ol>
        <li>
            <h3>Palenque, Chiapas</h3>
            <p>Sumérgete en la majestuosidad de la civilización maya explorando las ruinas de Palenque, rodeadas por exuberante vegetación tropical.</p>
        </li>
        <li>
            <h3>Calakmul, Campeche</h3>
            <p>Descubre la imponente reserva de la biosfera de Calakmul, hogar de una impresionante variedad de flora y fauna, así como de antiguas pirámides mayas.</p>
        </li>
        <li>
            <h3>Mérida, Yucatán</h3>
            <p>Sumérgete en la cultura yucateca explorando la encantadora ciudad colonial de Mérida, conocida por su arquitectura colonial, gastronomía única y festivales culturales.</p>
        </li>
        <li>
            <h3>Chichén Itzá, Yucatán</h3>
            <p>Maravíllate ante la grandeza de una de las Nuevas Maravillas del Mundo, la antigua ciudad maya de Chichén Itzá, con su famosa pirámide de Kukulcán.</p>
        </li>
        <li>
            <h3>Tulum, Quintana Roo</h3>
            <p>Relájate en las hermosas playas de Tulum y explora las ruinas de una ciudad costera maya con vista al mar Caribe.</p>
        </li>
    </ol>
</section>

<section>
    <h2>Consejos para Viajeros</h2>
    <ul>
        <li>Reserva con Anticipación</li>
        <li>Empaca de Forma Inteligente</li>
        <li>Respeta la Cultura Local</li>
        <li>Sé Responsable con el Medio Ambiente</li>
    </ul>
</section>

<section>
    <h2>Información Práctica</h2>
    <ul>
        <li>Cómo Llegar</li>
        <li>Horarios y Tarifas</li>
        <li>Alojamiento</li>
        <li>Seguridad</li>
    </ul>
</section>
{% endblock %}

porfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<!-- Hero Section -->
<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/.jpeg' %}" />
    </div>

    <div class="col-md-8 my-auto p-4">
        <h1>Bienvenid@ <strong>a la Pagina del tren Maya</strong></h1>
        <h3>Aquí podras encontrar:</h3>
       <a href="tickets/">Venta de Tickets</a>
       <hr>
        <a href="guia/">Guia turistica</a>
        <hr>
        <a href="puntos_interes/">Puntos de interes Geolocalizados</a>
        <hr>
        <a href="galeria/">Galería de imágenes</a>
    </div>
</header>

<!-- Porfolio Section -->
<div class="row my-4 text-center">

    <h3>Estaciones Tren maya</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, aperiam?</p>

    {% for project in projects %}
    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <img src="{{project.image.url }}" class="card-img-top" />

            <div class="card-body">

                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>

                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Visita
                    información</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

porfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Porfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

porfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="guia/">Guia turistica</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="puntos_interes/">Puntos de interes Geolocalizados</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

porfolio/templates/puntos_interes.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
<h1>Puntos de Interes Geolocalizados</h1>
<p>En esta sección podras encontrar los puntos de interes geolocalizados en el mapa</p>
{% endblock %}

porfolio/templates/tickets.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}


<div class="container">
    <h1>Compra de Tickets</h1>
    <p>En esta sección podrás comprar tus tickets para el tren maya</p>
    <p>Al momento de comprar tu ticket primero tienes que seleccionar el lugar de origen</p>
    <p>Después seleccionar el lugar de destino</p>
    <p>La fecha de salida</p>
    <p>Y por último la cantidad de tickets que deseas comprar</p>
    <a href="https://reservas.ventaboletostrenmaya.com.mx/" class="btn btn-primary">Comprar Tickets</a>
</div>
{% for imagen in imagenes %}
<img src="{{imagen.image.url }}" class="card-img-top" />
{% endfor %}
{% endblock %}